// <auto-generated />
using CustomSearchEngine.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomSearchEngine.Migrations
{
    [DbContext(typeof(CustomSearchEngineContext))]
    [Migration("20210110164149_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CustomSearchEngine.Models.SearchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("SearchEngine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SearchQuery")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SearchResults");
                });

            modelBuilder.Entity("CustomSearchEngine.Models.SearchResultItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SearchResultId")
                        .HasColumnType("int");

                    b.Property<string>("Snippet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SearchResultId");

                    b.ToTable("SearchResultItems");
                });

            modelBuilder.Entity("CustomSearchEngine.Models.SearchResultItem", b =>
                {
                    b.HasOne("CustomSearchEngine.Models.SearchResult", "SearchResult")
                        .WithMany("SearchResultItems")
                        .HasForeignKey("SearchResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchResult");
                });

            modelBuilder.Entity("CustomSearchEngine.Models.SearchResult", b =>
                {
                    b.Navigation("SearchResultItems");
                });
#pragma warning restore 612, 618
        }
    }
}
